from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from scripts.prepare_offline_lock import LockError, prepare_lock


class PrepareOfflineLockTests(unittest.TestCase):
    def test_adds_require_hashes_after_generated_header(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            source = Path(directory) / "source.lock"
            target = Path(directory) / "target.lock"
            source.write_text(
                "# generated by uv\npackage==1.0 \\\n+    --hash=sha256:" + "a" * 64 + "\n",
                encoding="utf-8",
            )

            prepare_lock(source, target)

            self.assertEqual(
                target.read_text(encoding="utf-8"),
                "# generated by uv\n--require-hashes\npackage==1.0 \\\n+    --hash=sha256:" + "a" * 64 + "\n",
            )

    def test_is_idempotent_when_gate_already_exists(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            source = Path(directory) / "source.lock"
            target = Path(directory) / "target.lock"
            content = "# generated by uv\n--require-hashes\npackage==1.0 --hash=sha256:" + "a" * 64 + "\n"
            source.write_text(content, encoding="utf-8")

            prepare_lock(source, target)

            self.assertEqual(target.read_text(encoding="utf-8"), content)

    def test_rejects_package_index_directives(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            source = Path(directory) / "source.lock"
            source.write_text(
                "--extra-index-url https://example.invalid/simple\n"
                "package==1.0 --hash=sha256:" + "a" * 64 + "\n",
                encoding="utf-8",
            )

            with self.assertRaisesRegex(LockError, "index or link directive"):
                prepare_lock(source, Path(directory) / "target.lock")


if __name__ == "__main__":
    unittest.main()
